apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gigapipe.fullname" . }}
  labels:
  {{- include "gigapipe.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
    {{- include "gigapipe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gigapipe.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      serviceAccountName: {{ include "gigapipe.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ include "gigapipe.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: "{{ $val }}"
          {{- end }}
          {{/* Use secret if CLICKHOUSE_AUTH not set in env */}}
          {{- if and (not .Values.env.CLICKHOUSE_AUTH) .Values.auth .Values.auth.clickhouse }}
          - name: CLICKHOUSE_AUTH
            valueFrom:
              secretKeyRef:
                name: {{ tpl ((.Values.auth.clickhouse.existingSecret) | default (include "gigapipe.fullname" .)) . }}
                key: CLICKHOUSE_AUTH
          {{- end }}
        {{- if .Values.envRenderSecret }}
        envFrom:
          - secretRef:
              name: {{ include "gigapipe.fullname" . }}-env
        {{- end }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP

        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if and .Values.readinessProbe .Values.readinessProbe.httpGet }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}

        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
