{{- if .Values.basicAuthPass -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth-{{ include "gigapipe.fullname" . }}
  namespace: {{ $.Release.Namespace }}
data:
  auth: {{ .Values.basicAuthPass | b64enc | quote }}
{{- end -}}
