{{- if .Values.serviceMonitor.enabled }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gigapipe.fullname" . }}
  labels:
    {{- include "gigapipe.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval | default "30s" }}
    path: /metrics
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "gigapipe.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}